name: dart_pg
description:  Dart PG (Dart Privacy Guard) - The OpenPGP implementation in Dart language.
version: 1.0.2
homepage: https://github.com/nguyennv/dart_pg

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  crypto: ^3.0.2
  fixnum: ^1.1.0
  pinenacl: ^0.5.1
  pointycastle: ^3.7.2

dev_dependencies:
  lints: ^2.0.0
  faker: ^2.0.0
  test: ^1.16.0

false_secrets:
 - /test/test_data.dart
 